### ISSUE TITLE
Duplicate Customer Field when activating installing crm_gautocomplete_address_form_extended

### ISSUE THREAD

**Issue by colpari** [mithnusa/odoo-google-maps#44]
Wen i install crm_gautocomplete_address_form_extended, the Customer field doubles in the crm.lead form view:

![image](https://github.com/mithnusa/odoo-addons/assets/74661552/f8c16f1b-49ed-4a30-87c5-041bd7acc498)

Odoo 16 CE, installed Modules:

![image](https://github.com/mithnusa/odoo-addons/assets/74661552/c12681aa-42ab-4052-9ecc-c70a2df403e5)

**Comment by gityopie** [comment]
@colpari Thanks for your feedback!
A new PR #45 is opened for the fixes

**Comment by gityopie** [comment]
It's merged :)
Just for your information, the fixes has been pushed to the [demo instance](http://35.209.158.83:8069/) as well.

Thanks @colpari

**Comment by colpari** [comment]
Ok, the duplicate customer field is gone now.

But the **extra address section**, which was located in the top of the form right after the customer field (see my first screenshot) is also gone.
This was very helpful (not having to go all the way down to "Extra Information).
We thought that was the main function of this _extended-module :grin:  Was it there by accident too?

**Comment by gityopie** [comment]
@colpari no, it was by accident 😄 
The main functionality of those extended module was related to the fields defined in module base_google_places, to enhance the Google Autocomplete widget by fulfill the information we get from the Google services into those fields, not just address, latitude, and longitude.  
<img width="511" alt="Screenshot 2024-02-07 at 01 00 31" src="https://github.com/mithnusa/odoo-addons/assets/3539144/72567b1f-f35a-4a1a-ba8b-ef1714e0c2f5">

**Comment by colpari** [comment]
Ok, thanks for the fix and thanks for the info :)
