### ISSUE TITLE
Feature Request: Restrict Countries for autocomplete search

### ISSUE THREAD

**Issue by gdgellatly** [mithnusa/odoo-google-maps#47]
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-multiple-countries

e.g. 
```javascript
// Set initial restriction to the greater list of countries.
  autocomplete.setComponentRestrictions({
    country: ["us", "pr", "vi", "gu", "mp"],
  });
```

For my use case the country of the company is fine, but I imagine it is easiest as an option in settings where if it is blank do nothing. My use case is a company which delivers only within its borders, so autocomplete addresses outside of this are very very rarely required.

**Comment by gityopie** [comment]
@gdgellatly Thank you for this feedback!
You are right, this feature is missing

**Comment by gityopie** [comment]
@gdgellatly The fixes has been pushed to the demo instance
v16: [http://35.209.158.83:8069](http://35.209.158.83:8069)
v17: [http://35.209.158.83:8080](http://35.209.158.83:8080)

username/password:
guest/guest

A new settings added:
<img width="479" alt="Screenshot 2024-02-27 at 18 57 08" src="https://github.com/mithnusa/odoo-addons/assets/3539144/0ca67b5f-eb92-422e-9014-23a91ba5df73">

I already set the restrictions to Australia and New Zealand

Please have a look and let me know your feedback
Thanks!

**Comment by gdgellatly** [comment]
@dannyadair Can you check for me please

**Comment by dannyadair** [comment]
LGTM

**Comment by gityopie** [comment]
@gdgellatly @dannyadair Thank you both!
If you have any other feedback, as always don't hesitate a new issue or discussion
