### ISSUE TITLE
Tampilan form view dari tombol di peta tidak sama dengan form view dari sidebar.

### ISSUE THREAD

**Issue by Ujeeee** [mithnusa/odoo-google-maps#54]
Saya menggunakan view yang diinherit dari modul contact. Tampilan form view yang dibuka dari sidebar google map sama dengan form view yang didesain di inherit form view, tapi tampilan form view yang dibuka dari tombol "Open" membuka default form view untuk modul contact.

Selain itu saat edit data dari form versi "pop-up" dari tombol open, akan error saat save. tapi data tetap berubah. hal ini juga saya konfirmasi di demo versi 17.

tombol ini
<img width="281" alt="Screenshot 2024-05-29 at 11 46 53" src="https://github.com/mithnusa/odoo-addons/assets/76468751/deb44d0e-8d79-4247-afdf-506ac1ca6b48">
buka form view ini
<img width="854" alt="Screenshot 2024-05-29 at 11 34 47" src="https://github.com/mithnusa/odoo-addons/assets/76468751/e7b5416b-6da0-40a3-bc7b-3bdcc7de8afe">

tombol sidebar
<img width="199" alt="Screenshot 2024-05-29 at 11 39 22" src="https://github.com/mithnusa/odoo-addons/assets/76468751/e9ab751f-d171-496d-b4f2-db7121a2f8af">
membuka form versi inherit
<img width="1037" alt="Screenshot 2024-05-29 at 11 40 07" src="https://github.com/mithnusa/odoo-addons/assets/76468751/6346484e-b6ec-4800-90a6-d86b34fc85d1">

gambar error saat save data dari form versi pop-up.
<img width="689" alt="Screenshot 2024-05-29 at 11 42 29" src="https://github.com/mithnusa/odoo-addons/assets/76468751/2d9da07f-db9d-47f6-99e2-21d13cdf79f1">

**Comment by gityopie** [comment]
Perbaikannya ada di PR #55 dan sudah di publish di branch [17.0](https://github.com/mithnusa/odoo-addons/tree/17.0)
Demo instance nya sudah sy update juga
Terima kasih banyak ya

Sedikit note kang, berhubung repo ini bukan cuma diakses orang Indo
Nanti kalau bisa pake English ya klo report issue

**Comment by Ujeeee** [comment]
Roger that.

**Comment by Ujeeee** [comment]
Hi again, I tested the updated version, the error bug is gone, but the view still go to the default form view.

**Comment by gityopie** [comment]
Can you share your custom view and which form view do you inherit?

**Comment by Ujeeee** [comment]
<record id="farmer_view_form" model="ir.ui.view">
        <field name="name">farmer.form.inherit.frm</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="priority">1000</field>
        <field name="mode">primary</field>
        <field name="arch" type="xml">
            <xpath expr="//page[@name='sales_purchases']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//page[@name='google_place']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//page[@name='contact_addresses']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='company_type']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='function']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='title']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='email']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='mobile']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='website']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>

        </field>
    </record>

**Comment by gityopie** [comment]
I guess you created a new menu where you link the new form view you created, correct?

The recent updated published to 17.0 branch was to ensure the form view that is opened is the one that associated with the current action.

In some of my modules, there are some fields added to the default `base.view_partner_form` and they are visible either the form is opened via the button on map sidebar or via the button on the marker infowindow.

**Comment by gityopie** [comment]
if you just want to add your customization to the default `base.view_partner_form`, remove this line `<field name="mode">primary</field>` in your custom view.

If you create a new action, make sure to link your custom view to it.

**Comment by Ujeeee** [comment]
Yes I am making new menu and new action, the custom form view successfully opened from tree view and kanban, and even in sidebar of the map view, but when opened from the info window in gmap view it return to default res.partner form view same as in contact module.

this is the action and view code. am I missing something?
<?xml version="1.0"?>
<odoo>

    <record id="farmer_view_kanban" model="ir.ui.view">
        <field name="name">farmer.kanban.inherit.frm</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.res_partner_kanban_view"/>
        <field name="priority">1000</field>
        <field name="mode">primary</field>
        <field name="arch" type="xml">
            <xpath expr="//ul" position="replace">
                <ul>
                    <li t-if="record.parent_id.raw_value and !record.function.raw_value"><field name="parent_id"/></li>
                    <li t-elif="!record.parent_id.raw_value and record.function.raw_value"><field name="function"/></li>
                    <li t-elif="record.parent_id.raw_value and record.function.raw_value"><field name="function"/> at <field name="parent_id"/></li>
                    <li t-if="record.city.raw_value or record.country_id.raw_value">
                        <t t-if="record.city.raw_value"><field name="city"/><t t-if="record.country_id.raw_value">, </t></t>
                        <t t-if="record.country_id.raw_value"><field name="country_id"/></t>
                    </li>
                    <li t-if="record.phone.raw_value" class="o_text_overflow"><field name="phone"/></li>
                </ul>
            </xpath>
        </field>
    </record>

    <record id="farmer_search" model="ir.ui.view">
        <field name="name">frm.farmer.search</field>
        <field name="model">res.partner</field>
        <field name="arch" type="xml">
            <search string="Search Properties">
                <field name="name"/>
                <field name="phone"/>
                <field name="spicehub"/>
                <filter string="Spicehub Unknown" name="spicehub_unknown" domain="[('spicehub', '=', False )]"/>
                <group expand="0" name="group_by" string="Group By">
                    <filter name="spicehub" string="Spicehub" context="{'group_by' : 'spicehub'}"/>
                </group>
            </search>
        </field>
    </record>

    <record id="farmer_view_tree" model="ir.ui.view">
        <field name="name">farmer.tree.inherit.frm</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_tree"/>
        <field name="priority">1000</field>
        <field name="mode">primary</field>
        <field name="arch" type="xml">
            <xpath expr="//tree" position="replace">
                <tree string="Farmer">
                    <field name="name"/>
                    <field name="gender"/>
                    <field name="birthdate"/>
                    <field name="ktp" optional="hide"/>
                    <field name="phone"/>
                    <field name="spicehub"/>
                    <field name="village"/>
                    <field name="rt" optional="hide"/>
                    <field name="rw" optional="hide"/>
                    <field name="subdistrict" optional="hide"/>
                    <field name="city" optional="hide"/>
                    <field name="country_id" optional="hide"/>
                    <field name="enrollment_date" optional="hide"/>
                    <field name="enrollment_id" optional="hide"/>
                    <field name="is_in_farmer_group" optional="hide"/>
                    <field name="agr_basic_training_progress" widget="progressbar" optional="show"/>
                    <field name="farmer_group_name" optional="hide"/>
                    <field name="comment" optional="hide"/>
                    <field name="contact_address_inline" optional="hide"/>
                </tree>
            </xpath>
        </field>
    </record>

    <record id="farmer_view_form" model="ir.ui.view">
        <field name="name">farmer.form.inherit.frm</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="base.view_partner_form"/>
        <field name="priority">1000</field>
        <field name="mode">primary</field>
        <field name="arch" type="xml">
            <xpath expr="//page[@name='sales_purchases']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//page[@name='google_place']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//page[@name='contact_addresses']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='company_type']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='function']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='title']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='email']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='mobile']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>
            <xpath expr="//field[@name='website']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>

        </field>
    </record>

    <record model="ir.actions.act_window.view" id="farmer_action_tree">
        <field name="view_mode">tree</field>
        <field name="view_id" ref="farmer_view_tree"/>
        <field name="act_window_id" ref="farmer_action2"/>
    </record>

    <record model="ir.actions.act_window.view" id="farmer_action_form">
        <field name="view_mode">form</field>
        <field name="view_id" ref="farmer_view_form"/>
        <field name="act_window_id" ref="farmer_action2"/>
    </record>

    <record model="ir.actions.act_window.view" id="farmer_action_kanban">
        <field name="view_mode">kanban</field>
        <field name="view_id" ref="farmer_view_kanban"/>
        <field name="act_window_id" ref="farmer_action2"/>
    </record>

    <record id="farmer_action2" model="ir.actions.act_window">
        <field name="name">List Petani</field>
        <field name="res_model">res.partner</field>
        <field name="view_mode">kanban,tree,form,google_map,activity</field>
        <field name="search_view_id" ref="farmer_search"/>
        <field name="view_id" ref="farmer_view_kanban"/>
        <field name="domain">[('is_farmer','=',True)]</field>
        <field name="context">{'default_is_farmer': True}</field>
    </record>

</odoo>

**Comment by gityopie** [comment]
The improvement is already published to the branch 17.0

Please have a look and let me know
Thank you!

**Comment by Ujeeee** [comment]
Thank you. Now it is working
